### ISSUE TITLE
Why? What? Who? How?

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/supabase-flutter-demo#1]
# Why?
**Supabase** is best known as *an open-source alternative to Google's [Firebase](https://firebase.google.com/)*. 
Although not an exact 1-1 mapping to Google's, Supabase is particularly useful for rapid development, as database, authentication and hosting concerns are contained in a [*black box*](https://en.wikipedia.org/wiki/Black_box), allowing us to focus solely on feature development.

This is a [SPIKE](https://en.wikipedia.org/wiki/Spike_(software_development)) project. It's meant to serve as a contained tutorial to check the viability of using Supabase with Flutter. The reason we're doing this is to check how *easy* it is to integrate authentication with Flutter and if it is viable on a long-term perspective.

# What?
As a Firebase alternative, there are some features that make Supabase different from Firebase. 
We recommend giving the following documentation link a whirl to know more about it.

https://supabase.com/docs/guides/getting-started/architecture

**Comment by nelsonic** [comment]
Was super duper looking forward to reading this tonight ... 🤞 

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/194400/215188572-3a67652a-70cd-4d06-bcec-74956e71a8f6.png">

But appears to be just the `main` branch: 🔍 

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/194400/215188659-016654e8-5abd-44fa-afaf-e05869e0c6c9.png">

And just an `initial commit`... ⏳ 

@LuchoTurtle in future, please remember to `git push` your work before you leave for the weekend. 🙏

**Comment by nelsonic** [comment]
Busy watching this now: 

Supabase Authentication & Realtime Database with Flutter: https://youtu.be/UTSSYPOd5A0
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/194400/215194687-c5c649fc-9163-432e-a6ed-b174415b2b46.png">

**Comment by nelsonic** [comment]
Sadly there is no buil-in mocking for `Supabase` ... 😢 
There was a feature request for it: https://github.com/supabase/supabase-dart/issues/12
but it was closed without any conclusive follow-up. 😕

**Comment by LuchoTurtle** [comment]
Should this be closed? The initial demo seems to be working 👀

**Comment by nelsonic** [comment]
Thanks for nudge. Closing. ✅
